export const ExpenseCategory = [
  {id: 'ec1', title: 'Food & Drinks', date: '2022-10-01'},
  {id: 'ec2', title: 'Transport', date: '2022-10-01'},
  {id: 'ec3', title: 'Home & Utilities', date: '2022-10-01'},
  {id: 'ec4', title: 'Leisure', date: '2022-10-01'},
  {id: 'ec5', title: 'Charity', date: '2022-10-01'},
  {id: 'ec6', title: 'Clothing & Footwear', date: '2022-10-01'},
  {id: 'ec7', title: 'Education', date: '2022-10-01'},
  {id: 'ec8', title: 'Gifts', date: '2022-10-01'},
  {id: 'ec9', title: 'Health & Personal Care', date: '2022-10-01'},
  {id: 'ec10', title: 'Loans', date: '2022-10-01'},
  {id: 'ec11', title: 'Sports', date: '2022-10-01'},
  {id: 'ec12', title: 'Taxes', date: '2022-10-01'},
  {id: 'ec13', title: 'Other', date: '2022-10-01'},
];

export const IncomeCategory = [
  {id: 'ic1', title: 'Salary', date: '2022-10-01'},
  {id: 'ic2', title: 'Allowance', date: '2022-11-15'},
  {id: 'ic3', title: 'Selling', date: '2022-10-17'},
  {id: 'ic4', title: 'Commission', date: '2022-10-18'},
  {id: 'ic5', title: 'Other', date: '2022-10-19'},
];

///////////////////////////// Transfer category ////////////////////////////////////////
export const TransferCategory = [
  {id: 'tc1', title: 'Children', date: '2022-09-01'},
  {id: 'tc2', title: 'Friends', date: '2022-09-05'},
  {id: 'tc3', title: 'Loan', date: '2022-09-10'},
  {id: 'tc4', title: 'Aids', date: '2022-09-12'},
  {id: 'tc5', title: 'Other', date: '2022-09-17'},
];

// export const TagsItems = [
//   {title: 'alcohol'},
//   {title: 'coffee & tea'},
//   {title: 'electricity'},
//   {title: 'groceries'},
//   {title: 'accessories'},
//   {title: 'accommodation'},
//   {title: 'adult fun'},
//   {title: 'airplane'},
//   {title: 'apps'},
//   {title: 'bicycle'},
//   {title: 'birthday'},
//   {title: 'books'},
//   {title: 'building upkeep'},
//   {title: 'bus'},
//   {title: 'car'},
//   {title: 'clothes'},
//   {title: 'cosmetics'},
//   {title: 'devices'},
//   {title: 'drugs'},
//   {title: 'equity purchase'},
//   {title: 'events'},
//   {title: 'ferry'},
//   {title: 'fuel'},
//   {title: 'furniture'},
//   {title: 'gambling'},
//   {title: 'games'},
//   {title: 'hairdresser'},
//   {title: 'heating'},
//   {title: 'home improvement'},
//   {title: 'income tax'},
//   {title: 'insurance'},
//   {title: 'internet'},
//   {title: 'landline phone'},
//   {title: 'lending'},
//   {title: 'loan repayment'},
//   {title: 'medical services'},
//   {title: 'medicine'},
//   {title: 'membership fees'},
//   {title: 'metro'},
//   {title: 'mobile phone'},
//   {title: 'motorbike'},
//   {title: 'movie & TV'},
//   {title: 'music'},
//   {title: 'parking'},
//   {title: 'plants'},
//   {title: 'property tax'},
//   {title: 'publications'},
//   {title: 'rent'},
//   {title: 'restaurants'},
//   {title: 'servicing'},
//   {title: 'shoes'},
//   {title: 'sightseeing'},
//   {title: 'soft drinks'},
//   {title: 'sport equipment'},
//   {title: 'sport ventures'},
//   {title: 'taxi'},
//   {title: 'tobacco'},
//   {title: 'toll'},
//   {title: 'train'},
//   {title: 'travel'},
//   {title: 'tuition'},
//   {title: 'water'},
// ];
