export const ExpenseCategory = [
  {id: 'ec1', title: 'Food & Drinks'},
  {id: 'ec2', title: 'Transport'},
  {id: 'ec3', title: 'Home & Utilities'},
  {id: 'ec4', title: 'Leisure'},
  {id: 'ec5', title: 'Charity'},
  {id: 'ec6', title: 'Clothing & Footwear'},
  {id: 'ec7', title: 'Education'},
  {id: 'ec8', title: 'Gifts'},
  {id: 'ec9', title: 'Health & Personal Care'},
  {id: 'ec10', title: 'Loans'},
  {id: 'ec11', title: 'Sports'},
  {id: 'ec12', title: 'Taxes'},
  {id: 'ec13', title: 'Other'},
];

export const IncomeCategory = [
  {id: 'ic1', title: 'Salary', date: new Date('2022-09-01')},
  {id: 'ic2', title: 'Allowance', date: new Date('2022-09-15')},
  {id: 'ic3', title: 'Selling', date: new Date('2022-09-17')},
  {id: 'ic4', title: 'Commission', date: new Date('2022-09-18')},
  {id: 'ic5', title: 'Other', date: new Date('2022-09-19')},
];

export const CashCategory = [
  {id: 'cash1', title: 'Cash', budget: '9500', date: new Date('2022-09-01')},
];

export const AccountCategory = [
  {id: 'acc1', title: 'Travel', budget: '2600', date: new Date('2022-09-05')},
  {id: 'acc2', title: 'Party', budget: '1800', date: new Date('2022-09-10')},
  {id: 'acc3', title: 'Business', budget: '4200', date: new Date('2022-09-13')},
  {id: 'acc4', title: 'Food', budget: '5500', date: new Date('2022-09-01')},
  {id: 'acc5', title: 'Leisure', budget: '2000', date: new Date('2022-09-14')},
  {
    id: 'acc6',
    title: 'Education',
    budget: '3600',
    date: new Date('2022-09-16'),
  },
  {id: 'acc7', title: 'Other', budget: '5600', date: new Date('2022-09-17')},
];

export const TransferCategory = [
  {id: 'tc1', title: 'Children', date: new Date('2022-09-01')},
  {id: 'tc2', title: 'Friends', date: new Date('2022-09-05')},
  {id: 'tc3', title: 'Loan', date: new Date('2022-09-10')},
  {id: 'tc4', title: 'Aids', date: new Date('2022-09-12')},
  {id: 'tc5', title: 'Other', date: new Date('2022-09-17')},
];

// export const TagsItems = [
//   {title: 'alcohol'},
//   {title: 'coffee & tea'},
//   {title: 'electricity'},
//   {title: 'groceries'},
//   {title: 'accessories'},
//   {title: 'accommodation'},
//   {title: 'adult fun'},
//   {title: 'airplane'},
//   {title: 'apps'},
//   {title: 'bicycle'},
//   {title: 'birthday'},
//   {title: 'books'},
//   {title: 'building upkeep'},
//   {title: 'bus'},
//   {title: 'car'},
//   {title: 'clothes'},
//   {title: 'cosmetics'},
//   {title: 'devices'},
//   {title: 'drugs'},
//   {title: 'equity purchase'},
//   {title: 'events'},
//   {title: 'ferry'},
//   {title: 'fuel'},
//   {title: 'furniture'},
//   {title: 'gambling'},
//   {title: 'games'},
//   {title: 'hairdresser'},
//   {title: 'heating'},
//   {title: 'home improvement'},
//   {title: 'income tax'},
//   {title: 'insurance'},
//   {title: 'internet'},
//   {title: 'landline phone'},
//   {title: 'lending'},
//   {title: 'loan repayment'},
//   {title: 'medical services'},
//   {title: 'medicine'},
//   {title: 'membership fees'},
//   {title: 'metro'},
//   {title: 'mobile phone'},
//   {title: 'motorbike'},
//   {title: 'movie & TV'},
//   {title: 'music'},
//   {title: 'parking'},
//   {title: 'plants'},
//   {title: 'property tax'},
//   {title: 'publications'},
//   {title: 'rent'},
//   {title: 'restaurants'},
//   {title: 'servicing'},
//   {title: 'shoes'},
//   {title: 'sightseeing'},
//   {title: 'soft drinks'},
//   {title: 'sport equipment'},
//   {title: 'sport ventures'},
//   {title: 'taxi'},
//   {title: 'tobacco'},
//   {title: 'toll'},
//   {title: 'train'},
//   {title: 'travel'},
//   {title: 'tuition'},
//   {title: 'water'},
// ];
